---
version: "2"
services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Chicago
      - ADVERTISE_IP="http://192.168.1.253:32400/"
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ALLOWED_NETWORKS=192.168.1.0/24
    volumes:
      - /zmedia/plex-config:/config
      - /zmedia/plex-transcode:/transcode
      - /zmedia/plex:/plex
    restart: always
