---
version: "2"
services:
  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /zmedia/unifi-config:/config
      - /zmedia/unifi-mongodb:/var/lib/mongodb
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: always
